# Generated by Django 4.0.2 on 2022-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
